services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - infra_influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=health_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    # No profile specified - this service starts by default
    networks:
      - shared-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - infra_mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - shared-network

  feature-api:
    build: ./app/
    container_name: feature-api
    ports:
      - "8000:8000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mytoken
      - INFLUX_ORG=MyOrg
      - INFLUX_BUCKET=health_data
      - ENV=dev
      - MONGO_URI=mongodb://root:secret@mongodb:27017
    volumes:
      - ./app:/app
    depends_on:
      - influxdb
      - mongodb
    profiles: ["app"]  # Only starts when "app" profile is activated
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network  # Named network instead of external
    external: true

volumes:
  infra_influxdb-data:
    external: true
  infra_mongo-data:
