services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - infra_influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=health_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    # No profile specified - this service starts by default
    networks:
      - shared-influx-network

  feature-api:
    build: ./app/
    container_name: feature-api
    ports:
      - "8000:8000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mytoken
      - INFLUX_ORG=MyOrg
      - INFLUX_BUCKET=health_data
      - ENV=dev
    volumes:
      - ./app:/app
    depends_on:
      - influxdb
    profiles: ["app"]  # Only starts when "app" profile is activated
    networks:
      - shared-influx-network

networks:
  shared-influx-network:
    name: shared-influx-network  # Named network instead of external
    external: true

volumes:
  infra_influxdb-data:
    external: true
