version: "3.9"

services:
  feature-api:
    build: .
    container_name: feature-api
    ports:
      - "8000:8000"
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=health
      - USE_REDIS=true
      - REDIS_HOST=redis
    depends_on:
      - influxdb
      - redis

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=health

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  influxdb-data:
  redis-data:

