version: "3.9"

services:
  feature-api:
    build: .
    container_name: feature-api
    ports:
      - "8000:8000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mytoken
      - INFLUX_ORG=MyOrg
      - INFLUX_BUCKET=health_data
    networks:
      - shared-influx-network

networks:
  shared-influx-network:
    external: true
